# Azure Pipelines
trigger:
- master

jobs:
- job: macOS
  timeoutInMinutes: 360
  pool:
    vmImage: 'macos-latest'

  steps:
  - script: ./ci/mac_ci_setup.sh
    displayName: 'Install dependencies'

  - script: ./ci/mac_ci_steps.sh
    displayName: 'Run Mac CI'
    env:
      BAZEL_REMOTE_CACHE: https://storage.googleapis.com/envoy-circleci-bazel-cache/

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/bazel-testlogs/**/test.xml'
      testRunTitle: 'macOS'
    condition: always()
