version: 2.1

executors:
  ubuntu-build:
    description: "A regular build executor based on ubuntu image"
    docker:
      # NOTE: Update this from https://github.com/envoyproxy/envoy-build-tools/blob/master/toolchains/rbe_toolchains_config.bzl#L8
      - image: envoyproxy/envoy-build-ubuntu:b480535e8423b5fd7c102fd30c92f4785519e33a
    resource_class: xlarge
    working_directory: /source

jobs:
   api:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run: ci/do_circle_ci.sh bazel.api
       - add_ssh_keys:
           fingerprints:
             - "fb:f3:fe:be:1c:b2:ec:b6:25:f9:7b:a6:87:54:02:8c"
       - run: ci/api_mirror.sh
       - store_artifacts:
           path: /build/envoy/generated
           destination: /

   go_control_plane_mirror:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run: ci/do_circle_ci.sh bazel.api
       - add_ssh_keys:
           fingerprints:
             - "9d:3b:fe:7c:09:3b:ce:a9:6a:de:de:41:fb:6b:52:62"
       - run: ci/go_mirror.sh

workflows:
  version: 2
  all:
    jobs:
      - api
      - go_control_plane_mirror
