blank_issues_enabled: false
contact_links:
  - name: "{Crash,security} bugs"
    url: https://github.com/envoyproxy/envoy/security/policy
    about: "Please file any crash or security bug with envoy-security@googlegroups.com."
