version: '2'
services:

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-proxy
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
      - ./envoy_wasm_example.wasm:/etc/envoy.wasm
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "18000:80"
      - "18001:8001"

  web_service:
    build:
      context: .
      dockerfile: Dockerfile-web-service
    networks:
      envoymesh:
        aliases:
          - web_service
    expose:
      - "80"
    ports:
      - "18080:80"

networks:
  envoymesh: {}
